### ISSUE TITLE
Nearest healthcare provider search

### ISSUE THREAD

**Issue by rohinmittal** [ramanpreeet1990/ATMedicine#5]
Multiple events being called.

When 'Locate nearest healthcare provider' is clicked, app is showing nearest providers but the screen is getting refreshed again and again.

Unable to go back to the home screen. Had to reboot my phone.

**Comment by ramanpreetSinghKhinda** [comment]
Happening because the condition to dismiss the progress bar was not verified correctly. Update the code. Issue is fixed is next release. Please check the attached apk 
https://github.com/ramanpreeet1990/ATMedicine/tree/master/submission/apk

Thank you
